[project]
name = "hummingbird-weather-assistant"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "dotenv>=0.9.9",
    "geocoder>=1.38.1",
    "openai>=2.5.0",
    "requests>=2.32.5",
    "streamlit>=1.50.0",
]
